# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-10 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.Module')),
                ('rid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='role.Role')),
            ],
        ),
    ]
