# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-10 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secId', models.CharField(max_length=20)),
                ('secName', models.CharField(max_length=30)),
            ],
        ),
    ]
