# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-10 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=20)),
                ('papersType', models.IntegerField()),
                ('papersNum', models.CharField(max_length=18)),
                ('phone', models.CharField(max_length=11)),
                ('telephone', models.CharField(max_length=11)),
                ('sex', models.IntegerField()),
                ('age', models.IntegerField()),
                ('birthday', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('degree', models.IntegerField()),
                ('remark', models.CharField(max_length=50)),
                ('hireDate', models.DateField()),
                ('sectionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='section.Section')),
            ],
        ),
    ]
